(function(g){var window=this;var dza=function(a,b){var c=[];g.qi(b,function(a){try{var b=g.uD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.tD(b)&&c.push(a):c.push(a)},a);
return c},eza=function(a,b){var c=dza(a,b);
(0,g.G)(c,function(a){g.uD.prototype.remove.call(this,a)},a)},fza=function(){var a=g.cH;
eza(a,a.g.Vd(!0))},R7=function(a,b){g.Q0.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.U=a;this.F={};this.P(a,"onMdxReceiversChange",this.I);this.P(a,"presentingplayerstatechange",this.I);this.I()},gza=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},hza=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},S7=function(){var a=gza();
a&&a(!1,"No cast extension found")},T7=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},U7=function(a){if(a>=g.Ora.length)S7();
else{var b=g.Ora[a],c="chrome-extension://"+b+g.Lra;0<=g.l2.indexOf(b)?hza(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,T7(c,S7)):U7(a+1)}):T7(c,function(){U7(a+1)})}},V7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},iza=function(){if(g.Mra){var a=2,b=gza(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;T7("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",S7,c)}},jza=function(){if(V7("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){iza();a({command:"cast.sender.init"});return}}if(!window.chrome||V7("Edge"))S7();else if(iza(),V7("Android")&&V7("Chrome/")&&window.navigator.presentation){a="";var b=g.Lh();55<=b?a="55":50<=b&&(a="50");T7("//www.gstatic.com/eureka/clank"+a+g.Lra,S7)}else U7(0)},kza=function(a){g.vG[a]&&(a=g.vG[a],(0,g.G)(a,function(a){g.tG[a]&&delete g.tG[a]}),a.length=0)},lza=function(a){var b=g.sG();
if(b)if(b.clear(a),a)kza(a);else for(var c in g.vG)kza(c)},mza=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Dg(a)||"";b&&(this.port=":"+b);this.domain=g.Cg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ya(a,"10.0")&&(this.o=!1))},nza=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},oza=function(){var a=window.document.createElement("a");
g.Wc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Za(a)},pza=function(a,b){var c=g.Bd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Xc(c,g.ae("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},qza=function(){var a=oza(),b=window.document.getElementById(a),c=b&&g.IF(b,"loaded");
c||b&&!c||(b=pza(a,function(){g.IF(b,"loaded")||(g.HF(b,"loaded","true"),g.zG(a),g.KE(g.Ea(lza,a),0))}))},rza=function(){var a=0<=g.Hb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.iL||a},W7=function(a){g.sH("cloudview",a)},X7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},Y7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},sza=function(a,b,c,d){var e=!1;
Y7()||(a=new g.tI(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.eH("yt-remote-cast-available",a);g.AG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){W7("onReceiverSelected: "+a.friendlyName);
g.eH("yt-remote-cast-receiver",a);g.AG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){W7("onReceiverResumed: "+a.friendlyName);
g.eH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){W7("onSessionChange: "+g.AH(a));
a||g.gH("yt-remote-cast-receiver");g.AG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
W7("cloudview.createSingleton_: "+e);return e},tza=function(a){W7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},uza=function(){W7("dispose");
var a=Y7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);tza(!1);g.xG(Z7);Z7.length=0},$7=function(){return!!g.fH("yt-remote-cast-installed")},vza=function(){var a=g.fH("yt-remote-cast-receiver");
return a?a.friendlyName:null},wza=function(){W7("clearCurrentReceiver");
g.gH("yt-remote-cast-receiver")},a8=function(a){g.sH("cloudview",a)},xza=function(){return $7()?Y7()?Y7().getCastSession():(a8("getCastSelector: Cast is not initialized."),null):(a8("getCastSelector: Cast API is not installed!"),null)},b8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},c8=function(){$7()?Y7()?b8()?(W7("Requesting cast selector."),Y7().requestSession()):(W7("Wait for cast API to be ready to request the session."),Z7.push(g.wG("yt-remote-cast2-api-ready",c8))):a8("requestCastSelector: Cast is not initialized."):
a8("requestCastSelector: Cast API is not installed!")},d8=function(a,b){b8()?Y7().setConnectedScreenStatus(a,b):a8("setConnectedScreenStatus called before ready.")},e8=function(a){W7("setCastInstalled_ "+a);
g.eH("yt-remote-cast-installed",a)},yza=function(a,b){Y7().init(a,b)},zza=function(a,b){e8(!0);
X7(!1);yza(a,function(a){a?(tza(!0),g.zG("yt-remote-cast2-api-ready")):(a8("Failed to initialize cast API."),e8(!1),g.gH("yt-remote-cast-available"),g.gH("yt-remote-cast-receiver"),uza());b(a)})},Aza=function(a,b,c,d,e,f,k){rza()?sza(b,e,f,k)&&(X7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?zza(a,c):(window.__onGCastApiAvailable=function(b,d){b?zza(a,c):(a8("Failed to load cast API: "+d),e8(!1),X7(!1),g.gH("yt-remote-cast-available"),g.gH("yt-remote-cast-receiver"),uza(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):qza():jza())):W7("Cannot initialize because not running Chrome")},g8=function(a,b){g.jG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.IB;this.A=this.o=null;this.I=(0,g.z)(this.UN,this);this.F=(0,g.z)(this.ol,this);this.G=(0,g.z)(this.TN,this);this.J=(0,g.z)(this.hO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.hu,this),Bza(this))):c=3;0!=c&&(b?this.hu(c):g.KE((0,g.z)(function(){this.hu(c)},this),0));
var d=xza();d&&f8(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},h8=function(a){return new g.zI(a.B.getPlayerContextData())},Bza=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Ea(this.lQ,a),this))},a)},Cza=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},i8=function(a,b){50>a.C.Hc()&&g.KB(a.C,b)},k8=function(a,b,c){var d=h8(a);
g.BI(d,c);-1E3!=d.g&&(d.g=b);j8(a,d)},l8=function(a,b,c){a.B.sendMessage(b,c)},j8=function(a,b){Cza(a);
a.B.setPlayerContextData(g.EI(b));Bza(a)},f8=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.ol(null));
a.A=b;a.A&&(m8("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.ol(a.A.media[0]))},Dza=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=h8(a);b.contentId!=d.videoId&&m8("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.BI(d,a.o.getEstimatedTime());j8(a,d)}else m8("No cast media video. Ignoring state update.")},m8=function(a){g.sH("CP",a)},n8=function(a,b,c){return(0,g.z)(function(a){this.Zb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Zb("Retrying "+b+" using MDx browser channel."),l8(this,b,c))},a)},o8=function(a){g.FH.call(this,"ScreenServiceProxy");
this.cd=a;this.o=[];this.o.push(this.cd.$_s("screenChange",(0,g.z)(this.zT,this)));this.o.push(this.cd.$_s("onlineScreenChange",(0,g.z)(this.RP,this)))},p8=function(){return g.x("yt.mdx.remote.currentScreenId_")},q8=function(a){g.sH("remote",a)},r8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},s8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},Eza=function(){var a=s8();
if(g.Xb(a)){a=g.LH();var b=g.fH("yt-remote-session-name")||"",c=g.fH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},Fza=function(a){a?(g.eH("yt-remote-session-app",a.app),g.eH("yt-remote-session-name",a.name)):(g.gH("yt-remote-session-app"),g.gH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},t8=function(){return g.x("yt.mdx.remote.connection_")},u8=function(){var a=t8();
return!!a&&3!=a.getProxyState()},Gza=function(){return g.x("yt.mdx.remote.connectData_")},w8=function(){if(!v8){var a=g.x("yt.mdx.remote.screenService_");
v8=a?new o8(a):null}return v8},x8=function(){var a=g.MH();
if(!a)return null;var b=w8().ee();return g.EH(b,a)},y8=function(){var a=p8();
if(!a)return null;var b=w8().ee();return g.EH(b,a)},Hza=function(){var a=w8().cd.$_gos();
var b=y8();b&&t8()&&(g.DH(a,b)||a.push(b));return nza(a)},Iza=function(){var a=Hza(),b=y8();
b||(b=x8());return g.fb(a,function(a){return b&&g.xH(b,a.key)?!0:!1})},z8=function(){var a=Iza();
!a&&$7()&&vza()&&(a={key:"cast-selector-receiver",name:vza()});return a},Jza=function(){var a=Hza();
$7()&&g.fH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Kza=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},B8=function(a){var b=t8();
r8(null);a||Kza("");g.ua("yt.mdx.remote.connection_",a,void 0);A8&&((0,g.G)(A8,function(b){b(a)}),A8.length=0);
b&&!a?g.AG("yt-remote-connection-change",!1):!b&&a&&g.AG("yt-remote-connection-change",!0)},D8=function(a,b){y8()&&y8();
Kza(a.id);var c=new g.KI(C8,a,s8());c.connect(b,Gza());c.subscribe("beforeDisconnect",function(a){g.AG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){t8()&&B8(null)});
B8(c)},Lza=function(){var a=x8();
a?(q8("Resume connection to: "+g.AH(a)),D8(a,0)):(g.TH(),wza(),q8("Skipping connecting because no session screen found."))},E8=function(){b8()?Y7().stopSession():a8("stopSession called before API ready.");
var a=t8();a&&(a.disconnect(1),B8(null))},Mza=function(a){q8("remote.onCastSessionChange_: "+g.AH(a));
if(a){var b=y8();b&&b.id==a.id?d8(b.id,"YouTube TV"):(b&&E8(),D8(a,1))}else t8()&&E8()},Nza=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.bE("MDX_CONFIG")||b;g.cH&&fza();g.NH();C8||(C8=new mza(b?b.loungeApiHost:void 0),g.VH()&&(C8.g="/api/loungedev"));A8||(A8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",A8,void 0));Eza();var c=w8();if(!c){var d=new g.fI(C8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=w8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Aza(a,d,function(a){a?p8()&&d8(p8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.AG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),q8("Initializing: "+g.ug(b)),F8.push(g.wG("yt-remote-cast2-availability-change",function(){g.AG("yt-remote-receiver-availability-change")})),F8.push(g.wG("yt-remote-cast2-receiver-selected",function(){r8(null);
g.AG("yt-remote-auto-connect","cast-selector-receiver")})),F8.push(g.wG("yt-remote-cast2-receiver-resumed",function(){g.AG("yt-remote-receiver-resumed","cast-selector-receiver")})),F8.push(g.wG("yt-remote-cast2-session-change",Mza)),F8.push(g.wG("yt-remote-connection-change",function(a){a?d8(p8(),"YouTube TV"):x8()||(d8(null,null),wza())})),a=s8(),b.isAuto&&(a.id+="#dial"),g.pF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),q8(" -- with channel params: "+
g.ug(a)),Fza(a),c.start(),p8()||Lza())},G8=function(a,b,c){g.L.call(this);
this.F=a;this.U=b;this.o=new g.gG(this);g.M(this,this.o);this.o.P(b,"onCaptionsTrackListChanged",this.kP);this.o.P(b,"captionschanged",this.SN);this.o.P(b,"captionssettingschanged",this.hC);this.o.P(b,"videoplayerreset",this.po);this.o.P(b,"mdxautoplaycancel",this.zG);this.N=this.o.P(b,"onVolumeChange",this.zA);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.MA,this);c.subscribe("remotePlayerChange",this.ql,this);c.subscribe("remoteQueueChange",this.po,this);c.subscribe("autoplayUpNext",this.mA,
this);c.subscribe("previousNextChange",this.JA,this);c.subscribe("nowAutoplaying",this.BA,this);c.subscribe("autoplayDismissed",this.lA,this);this.suggestion=null;this.G=new g.NQ(64);this.A=new g.wt(this.cC,500,this);g.M(this,this.A);this.B=new g.wt(this.dC,1E3,this);g.M(this,this.B);this.C={};this.J=new g.wt(this.FC,1E3,this);g.M(this,this.J);this.I=new g.nk(this.GK,1E3,this);g.M(this,this.I);this.L=g.y;this.hC();this.po();this.ql()},H8=function(a,b){var c=a.F,d=a.U.ga().lengthSeconds;
c.I=b||0;c.g.V("progresssync",b,d)},Oza=function(a){H8(a,0);
a.A.stop();I8(a,new g.NQ(64))},K8=function(a,b){if(J8(a)&&!a.D){var c=null;
b&&(c={style:a.U.li()},g.dc(c,b));a.g.VB(a.U.ga().videoId,c);a.C=h8(a.g).o}},L8=function(a,b){var c=a.U.Pf();
if(c){var d=c.ae();var e=c.listId.toString()}var f=a.U.ga();c=a.g;var k=a.U.ga().videoId,l=d;d=f.playerParams;f=f.mj;var m=h8(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};g.DI(m,k,l);g.t(b)&&(g.BI(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);l8(c,"setPlaylist",q);e||j8(c,m);I8(a,new g.NQ(1))},Pza=function(a,b){if(b){var c=a.U.uc("captions","tracklist",{Tx:1});
c&&c.length?(a.U.Cd("captions","track",b),a.D=!1):(a.U.al("captions"),a.D=!0)}else a.U.Cd("captions","track",{})},J8=function(a){return h8(a.g).videoId==a.U.ga().videoId},I8=function(a,b){a.B.stop();
var c=a.G;if(!g.SQ(c,b)){var d=g.W(b,2);if(d!=g.W(a.G,2)){var e=a.U;g.I1(e.app,d,e.playerType)}a.G=b;Qza(a.F,c,b)}},M8=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.gE()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.BX(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);Rza(this,g.zW(a))},Rza=function(a,b){if(3==a.A.Wa()){var c={RECEIVER_NAME:a.A.uc("remote","currentReceiver").name};
c=g.W(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.jb()||g.W(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},N8=function(a){g.tX.call(this,a);
this.A={key:g.CH(),name:g.T("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.NQ(64);this.I=0;var b=g.sW(a).G;b&&(b=b.A&&b.A.g)&&(b=new R7(a,b),g.M(this,b));b=new M8(a);g.M(this,b);g.SW(a,b.element,4)},Qza=function(a,b,c){a.F=c;
a.g.V("presentingplayerstatechange",new g.XQ(c,b))},O8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)E8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ga(1),e=d.videoId;if(c||e){var f=a.g.Pf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.gc(l).videoId}else k=[e];f=a.g.getCurrentTime();c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.mj,index:Math.max(a.g.dz(),0),currentTime:0==f?void 0:f}}else c=null;q8("Connecting to: "+g.ug(b));"cast-selector-receiver"==b.key?(r8(c||null),b8()?Y7().setLaunchParams(c||null):a8("setLaunchParams called before ready.")):!c&&
u8()&&p8()==b.key?g.AG("yt-remote-connection-change",!0):(E8(),r8(c||null),c=w8().ee(),(c=g.EH(c,b.key))&&D8(c,1))}};
g.p(R7,g.Q0);R7.prototype.I=function(){var a=this.U.uc("remote","receivers");a&&1<a.length&&!this.U.uc("remote","quickCast")?(this.F=g.Gb(a,this.B,this),g.R0(this,(0,g.J)(a,this.B)),a=this.U.uc("remote","currentReceiver"),this.kf(this.B(a)),this.enable(!0)):this.enable(!1)};
R7.prototype.B=function(a){return a.key};
R7.prototype.jf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
R7.prototype.qd=function(a){g.Q0.prototype.qd.call(this,a);this.U.Cd("remote","currentReceiver",this.F[a]);this.A.Kb()};
g.h=mza.prototype;g.h.Vh=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Mg(b+a,{})};
g.h.fu=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Tb:g.Ea(this.uT,c,!0),onError:g.Ea(this.tT,d),Ed:g.Ea(this.vT,d)};b&&(c.Mb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.$E(a,c)};
g.h.uT=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.tT=function(a,b){a(Error("Request error: "+b.status))};
g.h.vT=function(a){a(Error("request timed out"))};
var Z7=[];g.A(g8,g.jG);g.h=g8.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,n8(this,"play")):l8(this,"play"),k8(this,1,g.CI(h8(this))),this.V("remotePlayerChange")):i8(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,n8(this,"pause")):l8(this,"pause"),k8(this,2,g.CI(h8(this))),this.V("remotePlayerChange")):i8(this,this.pause)};
g.h.QC=function(a){if(1==this.g){if(this.o){var b=h8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,n8(this,"seekTo",{newTime:a}))}else l8(this,"seekTo",{newTime:a});k8(this,3,a);this.V("remotePlayerChange")}else i8(this,g.Ea(this.QC,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,n8(this,"stopVideo")):l8(this,"stopVideo");var a=h8(this);a.index=-1;a.videoId="";g.AI(a);j8(this,a);this.V("remotePlayerChange")}else i8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=h8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){m8("set receiver volume: "+d)},this),(0,g.z)(function(){this.Zb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){m8("set receiver muted: "+b)},this),(0,g.z)(function(){this.Zb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);l8(this,"setVolume",e)}c.muted=b;c.volume=a;j8(this,c)}else i8(this,g.Ea(this.setVolume,a,b))};
g.h.VB=function(a,b){if(1==this.g){var c=h8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.ug(b.style),g.dc(d,c.o));l8(this,"setSubtitlesTrack",d);j8(this,c)}else i8(this,g.Ea(this.VB,a,b))};
g.h.gu=function(a,b){if(1==this.g){l8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Qc.id});var c=h8(this);c.audioTrackId=b.Qc.id;j8(this,c)}else i8(this,g.Ea(this.gu,a,b))};
g.h.PC=function(a,b){if(1==this.g){if(a&&b){var c=h8(this);g.DI(c,a,b);j8(this,c)}l8(this,"previous")}else i8(this,g.Ea(this.PC,a,b))};
g.h.OC=function(a,b){if(1==this.g){if(a&&b){var c=h8(this);g.DI(c,a,b);j8(this,c)}l8(this,"next")}else i8(this,g.Ea(this.OC,a,b))};
g.h.mw=function(){1==this.g?l8(this,"dismissAutoplay"):i8(this,this.mw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.V("proxyStateChange",a,this.g)}g8.Z.dispose.call(this)};
g.h.X=function(){Cza(this);this.B=null;this.C.clear();f8(this,null);g8.Z.X.call(this)};
g.h.hu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.LB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.lQ=function(a,b){this.V(a,b)};
g.h.UN=function(a){if(!a)this.ol(null),f8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=h8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)m8("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,j8(this,b)}};
g.h.ol=function(a){m8("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Dza(this),this.V("remotePlayerChange")};
g.h.TN=function(a){a?(Dza(this),this.V("remotePlayerChange")):this.ol(null)};
g.h.hO=function(){var a=xza();a&&f8(this,a)};
g.h.Zb=function(a){g.sH("CP",a)};
g.A(o8,g.FH);g.h=o8.prototype;g.h.ee=function(a){return this.cd.$_gs(a)};
g.h.contains=function(a){return!!this.cd.$_c(a)};
g.h.get=function(a){return this.cd.$_g(a)};
g.h.start=function(){this.cd.$_st()};
g.h.qp=function(a,b,c){this.cd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.cd.$_r(a,b,c)};
g.h.Xo=function(a,b,c,d){this.cd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.cd.$_ubk(this.o[a]);this.o.length=0;this.cd=null;o8.Z.X.call(this)};
g.h.zT=function(){this.V("screenChange")};
g.h.RP=function(){this.V("onlineScreenChange")};
var C8=null,A8=null,F8=[],v8=null;g.p(G8,g.L);g.h=G8.prototype;g.h.X=function(){g.L.prototype.X.call(this);this.A.stop();this.B.stop();this.L();this.g.unsubscribe("proxyStateChange",this.MA,this);this.g.unsubscribe("remotePlayerChange",this.ql,this);this.g.unsubscribe("remoteQueueChange",this.po,this);this.g.unsubscribe("autoplayUpNext",this.mA,this);this.g.unsubscribe("previousNextChange",this.JA,this);this.g.unsubscribe("nowAutoplaying",this.BA,this);this.g.unsubscribe("autoplayDismissed",this.lA,this);this.g=this.F=null};
g.h.Ty=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(J8(this)){if(1081!=h8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":h8(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.bj(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.g.gu(this.U.ga().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.U.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.g.gu(this.U.ga().videoId,c)}};
g.h.SN=function(a){this.Ty("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.hC=function(){var a=this.U.uc("captions","track");g.Xb(a)||K8(this,a)};
g.h.zA=function(a){if(J8(this)){this.g.unsubscribe("remotePlayerChange",this.ql,this);var b=Math.round(a.volume);a=!!a.muted;var c=h8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.J.start();this.g.subscribe("remotePlayerChange",this.ql,this)}};
g.h.kP=function(){g.Xb(this.C)||Pza(this,this.C);this.D=!1};
g.h.MA=function(a,b){this.B.stop();2==b&&this.dC()};
g.h.ql=function(){if(J8(this)){this.A.stop();var a=h8(this.g);switch(a.g){case 1081:I8(this,new g.NQ(8));break;case 1:this.cC();I8(this,new g.NQ(8));break;case 1083:case 3:I8(this,new g.NQ(9));break;case 0:I8(this,new g.NQ(2));this.I.stop();H8(this,this.U.ga().lengthSeconds);break;case 1082:I8(this,new g.NQ(4));break;case 2:I8(this,new g.NQ(4));H8(this,g.CI(a));break;case -1:I8(this,new g.NQ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},I8(this,new g.NQ(128,
a))}a=h8(this.g).o;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,Pza(this,a));a=h8(this.g);-1==a.volume||Math.round(this.U.getVolume())==a.volume&&this.U.isMuted()==a.muted||this.J.isActive()||this.FC()}else Oza(this)};
g.h.JA=function(){this.U.V("mdxpreviousnextchange")};
g.h.po=function(){J8(this)||Oza(this)};
g.h.zG=function(){this.g.mw()};
g.h.mA=function(a){a&&(a=g.$E("/watch_queue_ajax",{method:"GET",Xc:{action_get_watch_queue_item:1,video_id:a},Tb:(0,g.z)(this.lR,this)}))&&(this.L=(0,g.z)(a.abort,a))};
g.h.lR=function(a,b){var c=new g.PP({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.U.V("mdxautoplayupnext",c)};
g.h.BA=function(a){(0,window.isNaN)(a)||this.U.V("mdxnowautoplaying",a)};
g.h.lA=function(){this.U.V("mdxautoplaycanceled")};
g.h.GK=function(a,b){-1==h8(this.g).g?L8(this,a):b&&this.g.QC(a)};
g.h.FC=function(){if(J8(this)){var a=h8(this.g);this.o.Ca(this.N);a.muted?this.U.mute():this.U.Qf();this.U.setVolume(a.volume);this.N=this.o.P(this.U,"onVolumeChange",this.zA)}};
g.h.cC=function(){this.A.stop();if(!this.g.ka()){var a=h8(this.g);a.jb()&&I8(this,new g.NQ(8));H8(this,g.CI(a));this.A.start()}};
g.h.dC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(M8,g.Y);M8.prototype.B=function(a){Rza(this,a.state)};g.p(N8,g.tX);g.h=N8.prototype;g.h.create=function(){Nza(g.RN(g.X(this.g)));this.D.push(g.wG("yt-remote-before-disconnect",this.ON,this));this.D.push(g.wG("yt-remote-connection-change",this.uQ,this));this.D.push(g.wG("yt-remote-receiver-availability-change",this.KA,this));this.D.push(g.wG("yt-remote-auto-connect",this.sQ,this));this.D.push(g.wG("yt-remote-receiver-resumed",this.rQ,this));this.KA()};
g.h.load=function(){this.g.Tp();g.tX.prototype.load.call(this);this.C=new G8(this,this.g,this.o);var a=Gza();a=a?a.currentTime:0;var b=u8()?new g8(t8(),void 0):null;0==a&&b&&(a=g.CI(h8(b)));0!=a&&(this.I=a||0,this.g.V("progresssync",a,void 0));Qza(this,this.F,this.F);g.M1(this.g.app,6)};
g.h.unload=function(){this.g.V("mdxautoplaycanceled");this.B=this.A;g.Xe(this.C,this.o);this.o=this.C=null;g.tX.prototype.unload.call(this);g.M1(this.g.app,5)};
g.h.X=function(){g.xG(this.D);g.tX.prototype.X.call(this)};
g.h.Uk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.Ty.apply(this.C,[].concat([a],g.pa(c)))};
g.h.mH=function(){return this.loaded?this.C.suggestion:null};
g.h.Ff=function(){return this.o?h8(this.o).Ff:!1};
g.h.hasNext=function(){return this.o?h8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.jK=function(){var a=h8(this.o),b=this.g.ga();return{allowSeeking:this.g.dd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.F)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.F)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.F?a.B+((0,g.F)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.F)()-a.A)/1E3:a.D}};
g.h.kK=function(){this.o&&this.o.OC()};
g.h.lK=function(){this.o&&this.o.PC()};
g.h.ON=function(a){1==a&&(this.J=this.o?h8(this.o):null)};
g.h.uQ=function(){var a=u8()?new g8(t8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.We(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.ga().videoId&&this.g.az(a.videoId,g.CI(a)));this.g.V("videodatachange","newdata",this.g.ga(),3)};
g.h.KA=function(){this.G=[this.A].concat(Jza());var a=z8()||this.A;O8(this,a);this.g.va("onMdxReceiversChange")};
g.h.sQ=function(){var a=z8();O8(this,a)};
g.h.rQ=function(){this.B=z8()};
g.h.iK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?c8():O8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&c8(),!0):!1}};
g.h.mK=function(){l8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.sd=function(){return!1};g.VZ.remote=N8;})(_yt_player);
